export const books = [
  {
    id: "1",
    title: "The Great Gatsby",
    authors: ["F. Scott Fitzgerald"],
    publishDate: "1925-04-10",
    coverUrl: "https://covers.openlibrary.org/b/id/10418284-L.jpg",
    rating: 4.5,
    status: "Read",
    finishDate: "2023-03-15",
  },
  {
    id: "2",
    title: "To Kill a Mockingbird",
    authors: ["Harper Lee"],
    publishDate: "1960-07-11",
    coverUrl: "/placeholder.svg",
    rating: 5,
    status: "Reading",
    startDate: "2023-04-01",
  },
  {
    id: "3",
    title: "1984",
    authors: ["George Orwell"],
    publishDate: "1949-06-08",
    coverUrl: "/placeholder.svg",
    rating: 4,
    status: "To Read",
  },
  {
    id: "4",
    title: "The Catcher in the Rye",
    authors: ["J.D. Salinger"],
    publishDate: "1951-07-16",
    coverUrl: "/placeholder.svg",
    rating: 3.5,
    status: "Read",
    finishDate: "2023-01-20",
  },
  {
    id: "5",
    title: "Pride and Prejudice",
    authors: ["Jane Austen"],
    publishDate: "1813-01-28",
    coverUrl: "/placeholder.svg",
    rating: 4.5,
    status: "To Read",
  },
  {
    id: "6",
    title: "The Hobbit",
    authors: ["J.R.R. Tolkien"],
    publishDate: "1937-09-21",
    coverUrl: "/placeholder.svg",
    rating: 5,
    status: "Reading",
    startDate: "2023-05-10",
  },
  {
    id: "7",
    title: "The Lord of the Rings",
    authors: ["J.R.R. Tolkien"],
    publishDate: "1954-07-29",
    coverUrl: "/placeholder.svg",
    rating: 5,
    status: "Read",
    finishDate: "2022-12-15",
  },
  {
    id: "8",
    title: "Brave New World",
    authors: ["Aldous Huxley"],
    publishDate: "1932-06-01",
    coverUrl: "/placeholder.svg",
    rating: 4,
    status: "To Read",
  },
  {
    id: "9",
    title: "The Odyssey",
    authors: ["Homer"],
    publishDate: "1890-01-01",
    coverUrl: "/placeholder.svg",
    rating: 4.5,
    status: "Read",
    finishDate: "2022-08-10",
  },
  {
    id: "10",
    title: "Moby Dick",
    authors: ["Herman Melville"],
    publishDate: "1851-10-18",
    coverUrl: "/placeholder.svg",
    rating: 4,
    status: "To Read",
  },
  {
    id: "11",
    title: "War and Peace",
    authors: ["Leo Tolstoy"],
    publishDate: "1869-01-01",
    coverUrl: "/placeholder.svg",
    rating: 5,
    status: "Reading",
    startDate: "2023-06-15",
  },
  {
    id: "12",
    title: "The Divine Comedy",
    authors: ["Dante Alighieri"],
    publishDate: "1320-01-01",
    coverUrl: "/placeholder.svg",
    rating: 4.5,
    status: "Read",
    finishDate: "2022-05-20",
  },
  {
    id: "13",
    title: "Crime and Punishment",
    authors: ["Fyodor Dostoevsky"],
    publishDate: "1866-01-01",
    coverUrl: "/placeholder.svg",
    rating: 4.5,
    status: "To Read",
  },
  {
    id: "14",
    title: "The Brothers Karamazov",
    authors: ["Fyodor Dostoevsky"],
    publishDate: "1880-01-01",
    coverUrl: "/placeholder.svg",
    rating: 5,
    status: "Read",
    finishDate: "2022-11-05",
  },
  {
    id: "15",
    title: "One Hundred Years of Solitude",
    authors: ["Gabriel García Márquez"],
    publishDate: "1967-05-30",
    coverUrl: "/placeholder.svg",
    rating: 4.5,
    status: "Reading",
    startDate: "2023-07-01",
  },
  {
    id: "16",
    title: "Don Quixote",
    authors: ["Miguel de Cervantes"],
    publishDate: "1605-01-01",
    coverUrl: "/placeholder.svg",
    rating: 4,
    status: "To Read",
  },
  {
    id: "17",
    title: "The Iliad",
    authors: ["Homer"],
    publishDate: "1890-01-01",
    coverUrl: "/placeholder.svg",
    rating: 4,
    status: "Read",
    finishDate: "2022-09-15",
  },
  {
    id: "18",
    title: "Anna Karenina",
    authors: ["Leo Tolstoy"],
    publishDate: "1877-01-01",
    coverUrl: "/placeholder.svg",
    rating: 4.5,
    status: "To Read",
  },
  {
    id: "19",
    title: "The Count of Monte Cristo",
    authors: ["Alexandre Dumas"],
    publishDate: "1844-01-01",
    coverUrl: "/placeholder.svg",
    rating: 5,
    status: "Reading",
    startDate: "2023-08-01",
  },
  {
    id: "20",
    title: "Les Misérables",
    authors: ["Victor Hugo"],
    publishDate: "1862-01-01",
    coverUrl: "/placeholder.svg",
    rating: 4.5,
    status: "Read",
    finishDate: "2022-07-10",
  },
];
