services:
  backend:
    build:
      context: ./api
    container_name: trackr-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URL=${DB_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}

  db:
    image: postgres:15
    container_name: trackr-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./web
    container_name: trackr-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

volumes:
  db-data:
